# https://helm.sh/docs/intro/install/
---
- name: Ensure helm is installed
  hosts: k8s01control k8s02control k8s03control
  become: true
  tasks:

    - name: Ensure apt helm repo key is installed
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/trusted.gpg.d/helm.asc
        mode: "0644"
      changed_when: false

    - name: Ensure helm repo is installed
      ansible.builtin.apt_repository:
        repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
        filename: helm
        state: present
        update_cache: true

    - name: Ensure helm is installed
      ansible.builtin.apt:
        name: helm
        update_cache: true

    - name: Ensure helm version is determined
      ansible.builtin.command: helm version
      register: result
      check_mode: false
      changed_when: false

    - name: Ensure helm version is shown
      ansible.builtin.debug:
        var: result.stdout
...
