---
- name: Ensure k8s cluster workers can run pods that use NFS data
  hosts: k8s01workers k8s02workers k8s03workers
  become: true

  tasks:

    - name: Ensure package to enable pods on workers to be NFS client is installed
      ansible.builtin.apt:
        name: nfs-common
        update_cache: true

...
